server:
  port: 8769
  
spring:
  application:
    name: service-zuul
  bus:
    trace:
      enabled: true
  stream:
    kafka:
      binder:
        brokers: localhost:2181

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
        
zuul:
  routes:
    api-a:
      path: /api-b/**
      serviceId: service-ribbon
    api-b:
      path: /api-a/**
      serviceId: service-feign
